version: '3.3'
services:
  postgres:
    image: postgres:16.4-bullseye
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${PG_DATABASE_PROD_USER}
      POSTGRES_PASSWORD: ${PG_DATABASE_PROD_PASSWORD}
      POSTGRES_DB: calvaryErpApi
    ports:
      - '5436:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
