# This configuration makes broad assumptions about intended use
# It's designed to work in development environment with dev script environment
# variables. Note that one carefully and check if you have missing keys in
# your environment
version: '3.3'
networks:
  calvary-erp-network:
    driver: bridge

services:
  postgres:
    image: postgres:16.4-bullseye
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${CALVARY_PG_DATABASE_DEV_USER}
      POSTGRES_PASSWORD: ${CALVARY_PG_DATABASE_DEV_PASSWORD}
      POSTGRES_DB: calvaryErpApiDev
    ports:
      - '5437:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    networks:
      - calvary-erp-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - ./pgadmindata:/var/lib/pgadmin
    networks:
      - calvary-erp-network
    depends_on:
      - postgres

  calvary-erp-elasticsearch:
    container_name: calvary_erp_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    volumes:
      - ./search-index-directory:/usr/share/elasticsearch/data
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 9301:9200
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9301/_cluster/health?wait_for_status=green&timeout=10s']
      interval: 5s
      timeout: 10s
      retries: 10

  consul:
    container_name: consul
    image: docker.io/bitnami/consul:1.19.1
    ports:
      - 127.0.0.1:8300:8300
      - 127.0.0.1:8500:8500
      - 127.0.0.1:8600:8600
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO
    networks:
      - calvary-erp-network

  consul-config-loader:
    container_name: consul_config_loader
    image: jhipster/consul-config-loader:v0.4.1
    volumes:
      - ./central-server-config:/config
    environment:
      - INIT_SLEEP_SECONDS=5
      - CONSUL_URL=consul
      - CONSUL_PORT=8500
      # Uncomment to load configuration into Consul from a Git repository
      # as configured in central-server-config/git2consul.json
      # Also set SPRING_CLOUD_CONSUL_CONFIG_FORMAT=files on your apps
      # - CONFIG_MODE=git
    networks:
      - calvary-erp-network

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
  pgadmindata:
    driver: local
  search-index-directory:
    driver: local
  central-server-config:
    driver: local
